name: cice-runtime

on:
  push:
    path:
      - ".github/workflows/runtime.yml"
      - "crates/cice-runtimes/**"
      - "crates/cice-core/**"
      - "Cargo.toml"
  pull_request:
    path:
      - ".github/workflows/runtime.yml"
      - "crates/cice-runtimes/**"
      - "crates/cice-core/**"
      - "Cargo.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  runtime-vnc:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
      - name: Install Nightly Rust Toolchain
        run: rustup update nightly
      - uses: Swatinem/rust-cache@v2
      - name: Build
        run: cargo build -p cice-runtime-vnc --verbose
      - name: Clippy
        run: cargo clippy -p cice-runtime-vnc --verbose
      - name: Run tests
        run: cargo test -p cice-runtime-vnc  --verbose
